<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141117183713 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE thinkopenat_timeflies_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, parent VARCHAR(40) DEFAULT NULL, name VARCHAR(80) NOT NULL, INDEX IDX_A49CD4FA3D8E604F (parent), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE thinkopenat_timeflies_domain_model_item (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, comment VARCHAR(200) NOT NULL, begin DATETIME NOT NULL, end DATETIME NOT NULL, INDEX IDX_1787FB6964C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE thinkopenat_timeflies_domain_model_category ADD CONSTRAINT FK_A49CD4FA3D8E604F FOREIGN KEY (parent) REFERENCES thinkopenat_timeflies_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE thinkopenat_timeflies_domain_model_item ADD CONSTRAINT FK_1787FB6964C19C1 FOREIGN KEY (category) REFERENCES thinkopenat_timeflies_domain_model_category (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE thinkopenat_timeflies_domain_model_category DROP FOREIGN KEY FK_A49CD4FA3D8E604F");
		$this->addSql("ALTER TABLE thinkopenat_timeflies_domain_model_item DROP FOREIGN KEY FK_1787FB6964C19C1");
		$this->addSql("DROP TABLE thinkopenat_timeflies_domain_model_category");
		$this->addSql("DROP TABLE thinkopenat_timeflies_domain_model_item");
	}
}